FROM golang:1.11-alpine as builder
WORKDIR /go/src/github.com/ceph/ceph-csi
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o  _output/rbdplugin ./rbd

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/github.com/ceph/ceph-csi/_output/rbdplugin .
CMD ["./rbdplugin"]
